services:
  nginx:
    image: nginx:1.27.0
    container_name: nginx-wordpress
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/wordpress-education
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm.Dockerfile
    container_name: php-wordpress-fpm
    volumes:
      - ./:/var/www/wordpress-education
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/hosts:/etc/hosts
    depends_on:
      - mysql

  php-cli:
    build:
      context: .
      dockerfile: docker/php-cli.Dockerfile
    container_name: php-wordpress-cli
    volumes:
      - ~/.ssh:/home/www-data/.ssh
      - ~/.bash_history:/home/www-data/.bash_history
      - ./:/var/www/wordpress-education
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/hosts:/etc/hosts
    tty: true
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-wordpress
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress-education
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: admin
    ports:
      - '3307:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: